//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Website {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Website() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Website", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not in correct format..
        /// </summary>
        internal static string DataInIncorrectFormat {
            get {
                return ResourceManager.GetString("DataInIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Time Entry..
        /// </summary>
        internal static string ErrorDeletingTimeEntry {
            get {
                return ResourceManager.GetString("ErrorDeletingTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Billable Option..
        /// </summary>
        internal static string ErrorFetchingBillableOption {
            get {
                return ResourceManager.GetString("ErrorFetchingBillableOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Clients Data..
        /// </summary>
        internal static string ErrorFetchingClientData {
            get {
                return ResourceManager.GetString("ErrorFetchingClientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Custom Templates..
        /// </summary>
        internal static string ErrorFetchingCustomTemplates {
            get {
                return ResourceManager.GetString("ErrorFetchingCustomTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Employee Options Data..
        /// </summary>
        internal static string ErrorFetchingEmployeeOptionsData {
            get {
                return ResourceManager.GetString("ErrorFetchingEmployeeOptionsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Projects Data..
        /// </summary>
        internal static string ErrorFetchingProjectData {
            get {
                return ResourceManager.GetString("ErrorFetchingProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Tasks Data..
        /// </summary>
        internal static string ErrorFetchingTaskData {
            get {
                return ResourceManager.GetString("ErrorFetchingTaskData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Time Entries..
        /// </summary>
        internal static string ErrorFetchingTimeEntries {
            get {
                return ResourceManager.GetString("ErrorFetchingTimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Time Entries Daily Total Data..
        /// </summary>
        internal static string ErrorFetchingTimeEntriesDailyTotalData {
            get {
                return ResourceManager.GetString("ErrorFetchingTimeEntriesDailyTotalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Time Entries Week Total Data..
        /// </summary>
        internal static string ErrorFetchingTimeEntriesWeekHoursDetailsData {
            get {
                return ResourceManager.GetString("ErrorFetchingTimeEntriesWeekHoursDetailsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching User Details..
        /// </summary>
        internal static string ErrorFetchingUserDetails {
            get {
                return ResourceManager.GetString("ErrorFetchingUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Time Entry..
        /// </summary>
        internal static string ErrorSavingTimeEntry {
            get {
                return ResourceManager.GetString("ErrorSavingTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Submitting Time Entry..
        /// </summary>
        internal static string ErrorSubmittingTimeEntry {
            get {
                return ResourceManager.GetString("ErrorSubmittingTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Failed..
        /// </summary>
        internal static string UnAuthorized {
            get {
                return ResourceManager.GetString("UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Failed..
        /// </summary>
        internal static string UnAuthorizedWithMessage {
            get {
                return ResourceManager.GetString("UnAuthorizedWithMessage", resourceCulture);
            }
        }
    }
}
